# Use an official Node runtime as a parent image
FROM node:16.14.0

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the client's source code
COPY . .

# Run any tests
CMD ["yarn", "test"]