name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.14'

      - name: Install yarn and run unittest
        run: |
          yarn
          yarn test
        env:
          CI: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/juliowebmaster:prod

      - name: Deploy to Vultr Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
              docker stop $(docker ps -a -q)
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/juliowebmaster:prod
              #docker run -dit -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/juliowebmaster:prod
              docker-compose up -d