name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.14'
      - name: Install yarn and run unittest
        run: |
          yarn
          yarn test
        env:
          CI: true
      - name: Publish to Docker Hub
        uses: docker/login-action@v1
        with:
          name: docker prod image
          #name: sourcecodeguy1/my-app/my-app
          #registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile-prod
          tags: latest
      - name: Deploy package to docker Server
        uses: appleboy/ssh-action@master
        #env:
         # GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          #envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull juliowebmaster:prod
            docker run -dit -p 80:80 juliowebmaster:prod
            docker logout docker.pkg.github.com
